import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <div className="w-full h-20 bg-purple-200 flex justify-evenly items-center">
          <Link
            href="/"
            className="text-purple-700 font-semibold text-md
             hover:text-purple-900 hover:scale-105"
          >
            All Books
          </Link>
          <Link
            href="/orders"
            className="text-purple-700 font-semibold text-md
             hover:text-purple-900 hover:scale-105"
          >
            All Orders
          </Link>
        </div> */}
        {children}
      </body>
    </html>
  );
}
